[languages]
fish = ["prettier"]
shell = ["shfmt -"]
bash = ["prettier"]
zsh = ["prettier"]
rust = ["rustfmt"]
vim = ["prettier"]
lua = ["stylua -s -"]
go = ["gofmt"]
python = ["black --fast -"]
javascript = ["prettier"]
json = ["prettier"]
jsonc = ["prettier"]
js = ["prettier"]
"ts annotate" = ["prettier"]
jsx = ["prettier"]
ts = ["prettier"]
tsx = ["prettier"]
typescript = ["prettier"]
react = ["prettier"]
astro = ["prettier"]
svelte = ["prettier --parser=svelte -"]
solidjs = ["prettier"]
css = ["prettierd"]
