# cyberdream theme for Alacritty

[colors.normal]
black = "0x16181a"
blue = "0x8aadf4"
cyan = "0x8bd5ca"
green = "0xa6da95"
magenta = "0xf5bde6"
red = "0xed8796"
white = "0xffffff"
yellow = "0xeed49f"

[colors.bright]
black = "0x494d64"
blue = "0x8aadf4"
cyan = "0x8bd5ca"
green = "0xa6da95"
magenta = "0xf5bde6"
red = "0xed8796"
white = "0xb8c0e0"
yellow = "0xeed49f"

[colors.primary]
background = "0x16181a"
foreground = "0xffffff"

[colors.selection]
background = "0x3c4048"
foreground = "0xffffff"

# Additional Colors (Inspired by Cyberdream)
[[colors.indexed_colors]]
color = "0xffbd5e" # A slightly warmer yellow/orange
index = 16

[[colors.indexed_colors]]
color = "0xb7bdf8" # A cool blue for accents
index = 17

# Tab bar 
active_tab_foreground = "0x16181a"
active_tab_background = "0xb7bdf8"
inactive_tab_foreground = "0xcad3f5"
inactive_tab_background = "0x1e2030"
tab_bar_background = "0x181926"
