return {
  "/Users/aaron/.config/nvim",
  "/Users/aaron/.local/share/nvim/site",
  "/Users/aaron/.local/share/nvim/lazy/lazy.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/mini.files",
  -- "/Users/aaron/.local/share/nvim/lazy/mini.surround",
  -- "/Users/aaron/.local/share/nvim/lazy/autolist.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/nvim-ts-context-commentstring",
  -- "/Users/aaron/.local/share/nvim/lazy/mini.bufremove",
  -- "/Users/aaron/.local/share/nvim/lazy/flit.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/sqlite.lua",
  -- "/Users/aaron/.local/share/nvim/lazy/yanky.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/fidget.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/garbage-day.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/lsp-lens.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/rainbow-delimiters.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/indent-blankline.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/mini.hipatterns",
  -- "/Users/aaron/.local/share/nvim/lazy/nvim-treesitter-context",
  -- "/Users/aaron/.local/share/nvim/lazy/bigfile.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/auto-indent.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/guess-indent.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/vim-illuminate",
  -- "/Users/aaron/.local/share/nvim/lazy/nvim-ts-autotag",
  -- "/Users/aaron/.local/share/nvim/lazy/mini.indentscope",
  -- "/Users/aaron/.local/share/nvim/lazy/gitsigns.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/todo-comments.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/elixir-tools.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/persistence.nvim",
  "/Users/aaron/.local/share/nvim/lazy/codeium.vim",
  -- "/Users/aaron/.local/share/nvim/lazy/better-escape.nvim",lus_la
  "/Users/aaron/.local/share/nvim/lazy/conform.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/nvim-lint",
  -- "/Users/aaron/.local/share/nvim/lazy/hydra.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/nvim-notify",
  -- "/Users/aaron/.local/share/nvim/lazy/edgy.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/nvim-early-retirement",
  -- "/Users/aaron/.local/share/nvim/lazy/mini.move",
  -- "/Users/aaron/.local/share/nvim/lazy/bufferline.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/cinnamon.nvim",
  "/Users/aaron/.local/share/nvim/lazy/mini.ai",
  -- "/Users/aaron/.local/share/nvim/lazy/vim-repeat",
  -- "/Users/aaron/.local/share/nvim/lazy/mini.comment",
  -- "/Users/aaron/.local/share/nvim/lazy/nvim-treesitter-textobjects",
  -- "/Users/aaron/.local/share/nvim/lazy/playground",
  -- "/Users/aaron/.local/share/nvim/lazy/tree-sitter-astro",
  -- "/Users/aaron/.local/share/nvim/lazy/nvim-treesitter-endwise",
  -- "/Users/aaron/.local/share/nvim/lazy/nvim-puppeteer",
  "/Users/aaron/.local/share/nvim/lazy/nvim-treesitter",
  -- "/Users/aaron/.local/share/nvim/lazy/no-neck-pain.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/mini.pairs",
  -- "/Users/aaron/.local/share/nvim/lazy/telescope-lazy.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/telescope-live-grep-args.nvim",
  "/Users/aaron/.local/share/nvim/lazy/noice.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/nvim-web-devicons",
  -- "/Users/aaron/.local/share/nvim/lazy/grapple.nvim",
  "/Users/aaron/.local/share/nvim/lazy/lualine.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/which-key.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/dashboard-nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/nvim-lua-gf",
  -- "/Users/aaron/.local/share/nvim/lazy/trouble.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/telescope-terraform.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/telescope-terraform-doc.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/telescope-fzf-native.nvim",
  "/Users/aaron/.local/share/nvim/lazy/telescope.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/yaml-companion.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/cyberdream",
  -- "/Users/aaron/.local/share/nvim/lazy/live-command.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/miasma",
  -- "/Users/aaron/.local/share/nvim/lazy/neogen",
  -- "/Users/aaron/.local/share/nvim/lazy/friendly-snippets",
  -- "/Users/aaron/.local/share/nvim/lazy/LuaSnip",
  -- "/Users/aaron/.local/share/nvim/lazy/cmp-dotenv",
  -- "/Users/aaron/.local/share/nvim/lazy/cmp_yanky",
  -- "/Users/aaron/.local/share/nvim/lazy/crates.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/tailwindcss-colorizer-cmp.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/cmp-treesitter",
  -- "/Users/aaron/.local/share/nvim/lazy/cmp-nvim-lua",
  -- "/Users/aaron/.local/share/nvim/lazy/cmp-cmdline",
  -- "/Users/aaron/.local/share/nvim/lazy/cmp_luasnip",
  -- "/Users/aaron/.local/share/nvim/lazy/cmp-path",
  -- "/Users/aaron/.local/share/nvim/lazy/cmp-buffer",
  "/Users/aaron/.local/share/nvim/lazy/nvim-cmp",
  "/Users/aaron/.local/share/nvim/lazy/copilot.lua",
  -- "/Users/aaron/.local/share/nvim/lazy/copilot-cmp",
  -- "/Users/aaron/.local/share/nvim/lazy/mini.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/mini.splitjoin",
  -- "/Users/aaron/.local/share/nvim/lazy/solarized",
  -- "/Users/aaron/.local/share/nvim/lazy/vimtex",
  -- "/Users/aaron/.local/share/nvim/lazy/ts-error-translator.nvim",
  -- "/Users/aaron/Code/nvim-plugins/leap.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/leap-spooky.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/smart-splits.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/vim-kitty",
  -- "/Users/aaron/.local/share/nvim/lazy/catppuccin",
  -- "/Users/aaron/.local/share/nvim/lazy/cmp-nvim-lsp",
  -- "/Users/aaron/.local/share/nvim/lazy/neoconf.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/neodev.nvim",
  "/Users/aaron/.local/share/nvim/lazy/nvim-lspconfig",
  "/Users/aaron/.local/share/nvim/lazy/mason.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/mason-lspconfig.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/tokyonight.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/LazyVim",
  -- "/Users/aaron/.local/share/nvim/lazy/plenary.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/nui.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/nvim-lsp-file-operations",
  -- "/Users/aaron/.local/share/nvim/lazy/neo-tree.nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/nfnl",
  "/Users/aaron/.local/share/bob/38b9c32/nvim-macos/share/nvim/runtime",
  "/Users/aaron/.local/share/bob/38b9c32/nvim-macos/share/nvim/runtime/pack/dist/opt/matchit",
  "/Users/aaron/.local/share/bob/38b9c32/nvim-macos/lib/nvim",
  -- "/Users/aaron/.local/share/nvim/lazy/indent-blankline.nvim/after",
  -- "/Users/aaron/.local/share/nvim/lazy/bigfile.nvim/after",
  -- "/Users/aaron/.local/share/nvim/lazy/playground/after",
  -- "/Users/aaron/.local/share/nvim/lazy/nvim-lua-gf/after",
  -- "/Users/aaron/.local/share/nvim/lazy/cmp-dotenv/after",
  -- "/Users/aaron/.local/share/nvim/lazy/cmp_yanky/after",
  -- "/Users/aaron/.local/share/nvim/lazy/cmp-treesitter/after",
  -- "/Users/aaron/.local/share/nvim/lazy/cmp-nvim-lua/after",
  -- "/Users/aaron/.local/share/nvim/lazy/cmp-cmdline/after",
  -- "/Users/aaron/.local/share/nvim/lazy/cmp_luasnip/after",
  -- "/Users/aaron/.local/share/nvim/lazy/cmp-path/after",
  -- "/Users/aaron/.local/share/nvim/lazy/cmp-buffer/after",
  -- "/Users/aaron/.local/share/nvim/lazy/vimtex/after",
  -- "/Users/aaron/.local/share/nvim/lazy/catppuccin/after",
  -- "/Users/aaron/.local/share/nvim/lazy/cmp-nvim-lsp/after",
  "/Users/aaron/.config/nvim/after",
  -- "/Users/aaron/.local/state/nvim/lazy/readme",
}
