-- NOTE: Originally tried to put this in FileType event autocmd but it is apparently too early for `set modifiable` to take effect
-- vim.api.nvim_create_autocmd("BufWinEnter", {
--   group = vim.api.nvim_create_augroup("quickfix", { clear = true }),
--   desc = "Allow updating quickfix window",
--   pattern = "quickfix",
--   callback = function(ctx)
--     vim.bo.modifiable = true
--     -- :vimgrep's quickfix window display format now includes start and end column (in vim and nvim) so adding 2nd format to match that
--     vim.bo.errorformat = "%f|%l col %c| %m,%f|%l col %c-%k| %m"
--     vim.keymap.set(
--       "n",
--       "<C-s>",
--       '<Cmd>cgetbuffer|set nomodified|echo "quickfix/location list updated"<CR>',
--       { buffer = true, desc = "Update quickfix/location list with changes made in quickfix window" }
--     )
--   end,
-- })

-- Fix telescope entering on insert mode
-- ac("WinLeave", {
--   callback = function()
--     if vim.bo.ft == "TelescopePrompt" and vim.fn.mode() == "i" then
--       vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Esc>", true, false, true), "i", false)
--     end
--   end,
-- })

-- no folding if buffer is bigger then 1 mb
-- TODO: need to used other then `opt` that is not correct here
-- vim.api.nvim_create_autocmd("BufReadPre", {
--   group = "disable_folding",
--   callback = function(ev)
--     local ok, size = pcall(vim.fn.getfsize, vim.api.nvim_buf_get_name(vim.fn.bufnr()))
--     if not ok or size > 1024 * 1024 then
--       -- fallback to default values
--       vim.opt.foldmethod = "manual"
--       vim.opt.foldexpr = "0"
--       vim.opt.foldlevel = 0
--       vim.opt.foldtext = "foldtext()"
--     else
--       vim.opt.foldmethod = "expr"
--       vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
--       vim.opt.foldlevel = 99
--       vim.opt.foldtext = "v:lua.vim.treesitter.foldtext()"
--     end
--   end,
-- })
