-- disable if using macos_option-as_alt in kitty
-- Keyboard remap for Mac fr
-- local symbol_key_opts = { desc = "which_key_ignore" }
-- For alacritty
-- if not vim.g.neovide then

-- map("n", "Ì", "<M-h>", symbol_key_opts)
-- map("n", "Ï", "<M-j>", symbol_key_opts)
-- map("n", "È", "<M-k>", symbol_key_opts)
-- map("n", "¬", "<M-l>", symbol_key_opts)
-- map("n", "æ", "<M-a>", symbol_key_opts)
-- map("n", "´", "<M-e>", symbol_key_opts)
-- map("n", "Â", "<M-z>", symbol_key_opts)
-- map("n", "®", "<M-r>", symbol_key_opts)
-- map("n", "†", "<M-t>", symbol_key_opts)
-- map("n", "Ú", "<M-y>", symbol_key_opts)
-- map("n", "º", "<M-u>", symbol_key_opts)
-- map("n", "î", "<M-i>", symbol_key_opts)
-- map("n", "œ", "<M-o>", symbol_key_opts)
-- map("n", "π", "<M-p>", symbol_key_opts)
-- map("n", "‡", "<M-q>", symbol_key_opts)
-- map("n", "Ò", "<M-s>", symbol_key_opts)
-- map("n", "∂", "<M-d>", symbol_key_opts)
-- map("n", "ƒ", "<M-f>", symbol_key_opts)
-- map("n", "ﬁ", "<M-g>", symbol_key_opts)
-- map("n", "µ", "<M-m>", symbol_key_opts)
-- map("n", "‹", "<M-w>", symbol_key_opts)
-- map("n", "≈", "<M-x>", symbol_key_opts)
-- map("n", "©", "<M-c>", symbol_key_opts)
-- map("n", "ç", "<M-c>", symbol_key_opts)
-- map("n", "√", "<M-v>", symbol_key_opts)
-- map("n", "√", "<M-v>", symbol_key_opts)
-- map("n", "ß", "<M-b>", symbol_key_opts)
-- map("n", "˜", "<M-n>") -- don't want to remap this one
-- -- map("n", "<M-S-a>", symbol_key_opts)
-- map("n", "¸", "<M-S-z>", symbol_key_opts)
-- map("n", "´", "<M-S-e>", symbol_key_opts)
-- map("n", "‰", "<M-S-r>", symbol_key_opts)
-- map("n", "ˇ", "<M-S-t>", symbol_key_opts)
-- map("n", "¨", "<M-S-u>", symbol_key_opts)
-- map("n", "ˆ", "<M-S-i>", symbol_key_opts)
-- map("n", "Ø", "<M-S-o>", symbol_key_opts)
-- map("n", "∏", "<M-S-p>", symbol_key_opts)
-- map("n", "Á", "<M-S-y>", symbol_key_opts)
-- -- map("n", "", "<M-S-q>", symbol_key_opts)
-- map("n", "Í", "<M-S-s>", symbol_key_opts)
-- map("n", "Î", "<M-S-d>", symbol_key_opts)
-- map("n", "Ï", "<M-S-f>", symbol_key_opts)
-- map("n", "˝", "<M-S-g>", symbol_key_opts)
-- -- map("n", "",  "<M-S-h>", symbol_key_opts)
-- -- map("n", "Í", "<M-S-j>", symbol_key_opts)
-- -- map("n", "Ë", "<M-S-k>", symbol_key_opts)
-- -- map("n", "|", "<M-S-l>") -- make conflicts I think cause it's a conditional key
-- map("n", "Â", "<M-S-m>", symbol_key_opts)
-- map("n", "„", "<M-S-w>", symbol_key_opts)
-- map("n", "˛", "<M-S-x>", symbol_key_opts)
-- map("n", "Ç", "<M-S-c>", symbol_key_opts)
-- map("n", "◊", "<M-S-v>", symbol_key_opts)
-- map("n", "ı", "<M-S-b>", symbol_key_opts)
-- map("n", "˜", "<M-S-n>", symbol_key_opts)
-- END Keyboard remap for Mac fr
-- end

-- local symbol_keys = {
--   "æ",
--   "Â",
--   "ê",
--   "®",
--   "†",
--   "Ú",
--   "º",
--   "î",
--   "œ",
--   "π",
--   "‡",
--   "Ò",
--   "∂",
--   "ƒ",
--   "ﬁ",
--   "Ì",
--   "Ï",
--   "È",
--   "¬",
--   "µ",
--   "‹",
--   "≈",
--   "©",
--   "◊",
--   "ß",
--   "Æ",
--   "Å",
--   "Ê",
--   "‚",
--   "™",
--   "ª",
--   "ï",
--   "Œ",
--   "∏",
--   "Ÿ",
--   "Ω",
--   "∑",
--   "∆",
--   "·",
--   "ﬂ",
--   "Î",
--   "Í",
--   "Ë",
--   "Ó",
--   "›",
--   "⁄",
--   "¢",
--   "√",
--   "∫",
--   "ı",
-- }

-- for _, key in ipairs(symbol_keys) do
--   map("n", "<A-" .. key .. ">", "<cmd>WhichKey '<A-" .. key .. ">'<cr>", { desc = "which_key_ignore" })
--   map("n", "<S-A-" .. key .. ">", "<cmd>WhichKey '<S-A-" .. key .. ">'<cr>", { desc = "which_key_ignore" })
-- end
