-- return {
--   {
--     "zbirenbaum/copilot.lua",
--     cmd = "Copilot",
--     build = ":Copilot auth",
--     event = "InsertEnter",
--     enabled = not vim.g.vscode,
--     opts = {
--       suggestion = { enabled = false },
--       panel = { enabled = false },
--       -- filetypes = {
--       --   markdown = true,
--       --   help = true,
--       -- },
--     },
--   },
-- }
return {
  {
    "zbirenbaum/copilot.lua",
    cmd = "Copilot",
    build = ":Copilot auth",
    event = "InsertEnter",
    opts = {
      suggestion = {
        -- enabled = false,
        -- auto_trigger = false,
        enabled = true,
        auto_trigger = true,
        -- MattFTW
        keymap = {
          -- accept = "<M-CR>",
          accept = "<A-CR>",
          accept_line = "<A-l>",
          accept_word = "<A-k>",
          next = "<A-]>",
          prev = "<A-[>",
          dismiss = "<A-c>",
        },
      },
      panel = { enabled = false },
      filetypes = {
        markdown = true,
        help = true,
        "javascript",
        "javascriptreact",
        "typescript",
        "typescript.tsx",
        "typescriptreact",
        "javascript",
        "javascript.jsx",
        "javascriptreact",
        "vue",
        "css",
        "scss",
        "less",
        "html",
        "json",
        "jsonc",
        "yaml",
        "markdown",
        "markdown.mdx",
        "markdown",
        "markdown.mdx",
        "graphql",
        "handlebars",
        "lua",
        "astro",
        "svelte",
        "vim",
        "python",
        "sh",
        "zsh",
        "bash",
        "fish",
        "zig",
        "go",
        "gohtml",
        "goimports",
      },
      keys = {
        { "<leader>cI", "<cmd>Copilot toggle<cr>", desc = "Toggle IA" },
        {
          ",c",
          function()
            require("copilot.panel").open({ "bottom", 0.25 })
          end,
          desc = "Toggle Copilot Panel",
        },
      },
    },
  },
}
