-- return {
--   {
--     "zbirenbaum/copilot.lua",
--     cmd = "Copilot",
--     build = ":Copilot auth",
--     event = "InsertEnter",
--     enabled = not vim.g.vscode,
--     opts = {
--       suggestion = { enabled = false },
--       panel = { enabled = false },
--       -- filetypes = {
--       --   markdown = true,
--       --   help = true,
--       -- },
--     },
--   },
-- }
return {
  {
    "zbirenbaum/copilot.lua",
    cmd = "Copilot",
    build = ":Copilot auth",
    event = "InsertEnter",
    opts = {
      suggestion = {
        enabled = false,
        -- auto_trigger = false,
        -- keymap = {
        --   -- accept = "<M-CR>",
        --   accept_line = "<M-l>",
        --   accept_word = "<M-k>",
        --   next = "<M-]>",
        --   prev = "<M-[>",
        --   dismiss = "<M-c>",
        -- },
      },
      panel = { enabled = false },
      filetypes = {
        markdown = true,
        help = true,
        "javascript",
        "javascriptreact",
        "typescript",
        "typescript.tsx",
        "typescriptreact",
        "javascript",
        "javascript.jsx",
        "javascriptreact",
        "vue",
        "css",
        "scss",
        "less",
        "html",
        "json",
        "jsonc",
        "yaml",
        "markdown",
        "markdown.mdx",
        "markdown",
        "markdown.mdx",
        "graphql",
        "handlebars",
        "lua",
        "astro",
        "svelte",
        "vim",
        "python",
        "sh",
        "zsh",
        "bash",
        "fish",
        "zig",
        "go",
        "gohtml",
        "goimports",
      },
      keys = {
        { "<leader>cI", "<cmd>Copilot toggle<cr>", desc = "Toggle IA" },
      },
    },
  },
}
