-- Omarchy-inspired Hammerspoon Configuration
-- Based on typical Hyprland/i3-style tiling window manager keybindings
-- Inspired by Omarchy's navigation patterns and hotkeys
--
-- Key Features:
-- - Uses Super/Cmd as the main modifier (like Hyprland/i3)
-- - Vim-style hjkl navigation for window focus
-- - Master-stack layout management
-- - Workspace/space navigation (1-9)
-- - Window swapping and resizing
-- - Quick application launching
-- - Floating window toggle
--
-- Usage:
-- 1. In your init.lua, add:
--    local omarchy = require("omarchy")
--    omarchy.init()
--
-- 2. Key bindings overview:
--    Super + Space         - Application launcher (Raycast)
--    Super + Return        - Terminal (Kitty)
--    Super + w             - Close window
--    Super + f             - Toggle fullscreen
--    Super + hjkl          - Focus window in direction
--    Super + Shift + hjkl  - Move window between screens
--    Super + Ctrl + hjkl   - Resize window
--    Super + t             - Apply tiled layout
--    Super + Tab           - Cycle windows forward
--    Super + 1-9           - Go to workspace
--    Super + Shift + 1-9   - Move window to workspace
--    Super + Alt + hjkl    - Snap window to screen halves
--    Super + Alt + uinm    - Snap window to quarters
--    Super + Alt + c       - Center window
--    Super + Shift + r     - Reload Hammerspoon
--    Super + Shift + q     - Lock screen

return require("omarchy.bk.init")
