[icon]
prepend_dirs = [
  { name = "desktop", text = "" },
  { name = "dev", text = "" },
  { name = "documents", text = "" },
  { name = "downloads", text = "" },
  { name = "music", text = "" },
  { name = "games", text = "󰊴" },
  { name = "pictures", text = "" },
  { name = "videos", text = "" },
]

[flavor]
use = "catppuccin-macchiato"
