std = "neovim"

[rules]
global_usage = "allow"
if_same_then_else = "allow"
incorrect_standard_library_use = "allow"
mixed_table = "allow"
multiple_statements = "allow"

[globals]
LazyVim = { any = true }
MiniExtra = { any = true }
MiniDiff = { any = true }
